name:
    github-action-docker-build

description:
    an extremely simple docker image auto build tool for your repository

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - shell: bash
      run: |
        docker login -u  ${{ github.repository_owner }} \
                     -p "${{ github.token }}" \
                         ghcr.io

        sed -i /^FROM\ /'a\
        \
        LABEL org.opencontainers.image.source="https://github.com/${{ github.repository }}"
        ' dockerfile

        docker build -t  ghcr.io/${{ github.repository}}:${{ github.ref_name }} .
        
        docker push      ghcr.io/${{ github.repository}}:${{ github.ref_name }}
